web:
  image: andrewhao/velocitas-core:latest
  ports:
    - "3000:3000"
  links:
    - db
  env_file:
    - ".env.web"

proxy:
  build: andrewhao/velocitas-proxy:latest
  ports:
    - "80:80"
  links:
    - web

db:
  image: mdillon/postgis:latest
  ports:
    - "15432:5432"
  env_file:
    - ".env.db"
