web:
  image: andrewhao/velocitas-core:latest
  ports:
    - "80:3000"
  links:
    - db
  env_file:
    - ".env.web"

db:
  image: mdillon/postgis:latest
  ports:
    - "15432:5432"
  env_file:
    - ".env.db"
